services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
      - ${ADMIN_API_PORT:-2019}:2019
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_config:/config
      - caddy_data:/data
    restart: unless-stopped
    networks:
      - caddy
  nginx.test:
    image: nginx:1.27-alpine-slim
    ports:
      - ${NGINX_PORT:-8080}:80
    restart: unless-stopped
    networks:
      - caddy

volumes:
  caddy_config:
  caddy_data:

networks:
  caddy:
    external: true
